### ISSUE TITLE
Ghost effect

### ISSUE THREAD

**Issue by hulkco** [zkarcher/FancyEPD#10]
Thanks @zkarcher , the rotate option already works, only that it presents the phantom effect from time to time.

[Video & picture](https://twitter.com/gsreynaga/status/903956447918215168)

**Comment by zkarcher** [comment]
Can you send me the code for the sequence in the video?

**Comment by hulkco** [comment]
This its
`//ESP8266 Section
#include <ESP8266WiFi.h>
const char* ssid     = "xxxx";
const char* password = "xxxx";

#include <stdint.h>
#include <Adafruit_GFX.h>
#include <FancyEPD.h>

#define DELAY_BETWEEN_IMAGES_MS       (6 * 1000)
#define DO_ROTATION                   (true)

// initialize epaper with pin numbers for cs, dc, rs, bs, d0, d1 for software SPI
//CS=15,DC=2,RS=0,BS=4, D0=14, D1=13
//EPD215 epaper( 15, 2, 0, 4, 14, 13 ); //ESP-12 PINOUT
FancyEPD epd(k_epd_model_E2215CS062, 15, 2, 5, 4, 14, 13 ); //ESP-12 PINOUT

void setup() {
  // put your setup code here, to run once:
   WiFi.begin(ssid, password);
   while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    
  }
  
  bool success = epd.init();
  epd.clearBuffer();

  if (!success) {
    // Panic and freak out
    return;
  }

}

void loop() {
  // put your main code here, to run repeatedly:
  
  if (DO_ROTATION) epd.setRotation(0);
  testdrawchar();
  drawLabel("Update 0: no blink, WiFi connected\n IP address: ");
  epd.println(WiFi.localIP());
  epd.updateScreen(k_update_no_blink);
  delay(DELAY_BETWEEN_IMAGES_MS);

  if (DO_ROTATION) epd.setRotation(1);
  testdrawchar();
  drawLabel("Update 1: no blink, WiFi connected\n IP address: ");
  epd.println(WiFi.localIP());
  epd.setBorderColor(0x00); // white
  epd.updateScreen(k_update_no_blink);
  delay(DELAY_BETWEEN_IMAGES_MS);

  if (DO_ROTATION) epd.setRotation(2);
  testdrawchar();
  drawLabel("Update 2: no blink, WiFi connected\n IP address: ");
  epd.println(WiFi.localIP());
  epd.setBorderColor(0x00); // white
  epd.updateScreen(k_update_no_blink);
  delay(DELAY_BETWEEN_IMAGES_MS);

  if (DO_ROTATION) epd.setRotation(3);
  testdrawchar();
  drawLabel("Update 3: no blink, WiFi connected\n IP address: ");
  epd.println(WiFi.localIP());
  epd.setBorderColor(0x00); // white
  epd.updateScreen(k_update_no_blink);
  delay(DELAY_BETWEEN_IMAGES_MS);

}

void drawLabel(String str)
{
  // Background box
  const uint8_t box_height = 35;
  epd.fillRect(0, 0, epd.width(), box_height, 0x0);
  epd.drawFastHLine(0, box_height, epd.width(), 0xff);
  epd.setCursor(0, 0);
  epd.print(str);
}

void testdrawchar(void) {
  
  //epd.setTextSize(1);
  epd.clearBuffer();
  epd.setCursor(0,40);

  for (uint8_t i=0; i < 208; i++) {
    if (i == '\n') continue;
    epd.write(i);
    //if ((i > 0) && (i % 14 == 0))
    //epd.println();
  }    
  //display.display();
}`

**Comment by zkarcher** [comment]
Thanks @hulkco ! I can reproduce the ghosting issue here. The ghosting may be an inherent limitation of ePaper displays.

In `FancyEPD.cpp::sendWaveforms()`, I tried changing the duration of `k_update_no_blink` from `20` to `40`, it does not fix the ghosting. `60` is a little better, so we could add another mode like `k_update_no_blink_long`, but it won't eliminate all ghosting effects.

It may be possible to reduce ghosting by applying higher voltages. I haven't explored this yet.

Right now, the best fix may to apply `k_update_quick_refresh` every 4 or 5 updates. This resets the pixel charges. I have an eReader which does this (Kobo Aura One). The flash is annoying, but it does help reduce ghosting.

**Comment by zkarcher** [comment]
Fixed: For 1-bit monochrome images, the `k_update_auto` mode usually redraws with no blink, and does a blinking refresh every 5th update. This helps eliminate ghosting. It's not perfect, but that's ePaper for ya 😄 

I opened ticket #14, I'd like to revisit this after the v1.0 release.
