### ISSUE TITLE
Increase SPI speed

### ISSUE THREAD

**Issue by zkarcher** [zkarcher/FancyEPD#2]
What is the maximum SPI speed your device can use? This is controlled by the first parameter in SPISettings. If you are using a chip rated at 15 MHz, use 15000000. Arduino will automatically use the best speed that is equal to or less than the number you use with SPISettings.
   ^^ faster?
	 https://www.pjrc.com/teensy/td_libs_SPI.html

 (1 second) / (250 nanoseconds) =
 4 000 000

Try 2x faster? That's the _whole_ clock cycle time

**Comment by pdp7** [comment]
My design could be improved by using the hardware SPI pins.

**Comment by zkarcher** [comment]
@pdp7 I think my board is using the correct pins for hardware SPI? On Teensy LC, SCK=13 and MOSI=11. These two constructor statements (in _FancyEPD_demo.ino_) seem to function the same, so yay:

`FancyEPD epd(k_epd_model_E2215CS062, 17, 16, 14, 15, 13, 11);	// software SPI`

`FancyEPD epd(k_epd_model_E2215CS062, 17, 16, 14, 15);	// hardware SPI`

**Comment by pdp7** [comment]
Oh awesome, I guess I just never tried the hardware SPI option.
