### ISSUE TITLE
Rotation option

### ISSUE THREAD

**Issue by hulkco** [zkarcher/FancyEPD#6]
Hello could you add the option and examples of how to rotate images and texts? Thank you.

**Comment by pdp7** [comment]
FYI - this is a quick hack I used to set rotation of e-paper display with @jarek319 EPD215 based on [Adafruit documentation](https://learn.adafruit.com/adafruit-gfx-graphics-library/rotating-the-display): 
* https://github.com/pdp7/EPD215/commit/f4e22660877759e53a3a83ed35c6e7a54616d285

#### [kicad-teensy-epaper badge](https://github.com/pdp7/kicad-teensy-epaper):
* Landscape mode:
   * `_rotation = 1`
* Portrait mode:
  * `_rotation = 2`


**TODO:** library should be modified to accept rotation parameter

**Comment by hulkco** [comment]
Thanks @zkarcher the rotate option already wo4ks, only that it presents the ghost effect from time to time.
[Video](https://twitter.com/gsreynaga/status/903956447918215168)
[Picture](https://twitter.com/gsreynaga/status/903956859169767424)
@pdp7
